### ISSUE TITLE
Terrain checkbox in OV2 export dialog does not work properly

### ISSUE THREAD

**Issue by theunderminer** [GlobalcachingEU/GAPP#4]
In ExportOV2Form.cs line 88:

`PluginSettings.Instance.gcTerrain = this.checkBoxOwner.Checked;`

should be:

`PluginSettings.Instance.gcTerrain = this.checkBoxTerrain.Checked;`

**Comment by Globalcaching** [comment]
Thanks for reporting this. Fix is committed and will be available in next release (2.0.12.0)
